[Draft] Org IdPs
p2-inc/keycloak-ui pull request #10
Opened 2022-11-30 05:08 UTC by pnzrr

- Separates items into components 
- Full stub for IdPs with need to plug in data

<img width="1145" alt="image" src="https://user-images.githubusercontent.com/93841792/204712278-0c11570e-3e7f-4dee-8e83-300402f75836.png">

2022-12-06 10:17 UTC, xgp requested changes
need to update the `updateIdentityProvider` api you're using. otherwise LGTM!

2022-12-07 03:44 UTC, pnzrr commented on apps/admin-ui/src/orgs/useOrgFetcher.ts
> +  async function getIdentityProviders(orgId: string) {
Yeah this one isn't in use. It's `adminClient`. I'll pull this method.

2022-12-07 03:51 UTC, pnzrr commented on apps/admin-ui/src/orgs/useOrgFetcher.ts
> +  async function updateIdentityProvider(
Updated the API method to use the correct one.

2022-12-07 03:52 UTC, pnzrr commented
Right now, there is a CORs error when trying to update from localhost. I was not able to fully verify yet.

2022-12-07 08:50 UTC, xgp approved these changes
:+1:

2022-12-07 08:51 UTC, merged